import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { AiFillRightCircle } from "react-icons/ai";
export default function Home() {
	const router = useRouter();
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-1 flex-col items-center justify-start gap-8 p-6 text-gray-dark">
				<img src="map.png" alt="" className="max-w-md"/>
				<button
					className="flex h-28 w-full max-w-xl select-none items-center justify-center gap-8 rounded-xl border border-gray bg-black text-start active:bg-gray "
					onClick={() => router.push("/home")}>
					<div className="w-[60%]">
						<p className="text-lg font-bold">Customer</p>
						<p className="text-xs">
							Normal account to make orders and get shipped
						</p>
					</div>
					<div>
						<AiFillRightCircle
							className="text-[28px] text-primary"
							width={64}
						/>
					</div>
				</button>
				<button
					className="flex h-28 w-full max-w-xl select-none items-center justify-center gap-8 rounded-xl border border-gray bg-black text-start active:bg-gray "
					onClick={() => router.push("/meals")}>
					<div className="w-[60%]">
						<p className="text-lg font-bold">Operator</p>
						<p className="text-xs">
							Admin account to manage orders and menu
						</p>
					</div>
					<div>
						<AiFillRightCircle
							className="text-[28px] text-primary"
							width={64}
						/>
					</div>
				</button>
			</div>
		</>
	);
}
