import { Meal } from "@/data/cartAtom";
import {
	filteredOrdersList,
	Order,
	orderFilterAtom,
	ordersAtom,
} from "@/data/ordersAtom";
import { db } from "@/util/firestore";
import { collection, getDocs } from "firebase/firestore";
import Head from "next/head";
import * as React from "react";
import { useState, useEffect } from "react";
import { BsCashStack, BsClockFill } from "react-icons/bs";
import { useRecoilState, useRecoilValue } from "recoil";
interface IAppProps {}

const App: React.FunctionComponent<IAppProps> = (props) => {
	const [filter, setFilter] = useRecoilState(orderFilterAtom);
	const [orders, setOrders] = useRecoilState(ordersAtom);
	const list = useRecoilValue(filteredOrdersList);

	useEffect(() => {
		async function fetchOrders() {
			let arr: Order[] = [];
			const querySnapshot = await getDocs(collection(db, "orders"));
			querySnapshot.forEach((doc) => {
				const data = doc.data();
				const id = doc.id;
				const order = { ...data, id };
				arr.push(order as Order);
			});
			setOrders(arr);
		}

		fetchOrders();
	}, []);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex max-w-xl flex-1 flex-col items-center justify-start gap-4 overflow-y-scroll p-6 text-white">
				{/* Filters */}
				<div className="flex w-full gap-3">
					<button
						className={`bg-${
							filter === "pending" ? "primary" : "black"
						} h-10 w-32 rounded-md transition-[1s] ${
							filter !== "pending" && "border border-gray"
						} flex items-center justify-center gap-3 text-xs font-bold text-[white]`}
						onClick={() => setFilter("pending")}>
						<BsClockFill className="text-xs" />
						<p>Pending</p>
					</button>
					<button
						className={`bg-${
							filter === "all" ? "primary" : "black"
						} h-10 w-32 transition-[1s] ${
							filter !== "all" && "border border-gray"
						} flex items-center justify-center gap-3 rounded-md text-xs font-bold text-[white]`}
						onClick={() => setFilter("all")}>
						<BsCashStack className="" />
						<p>All orders</p>
					</button>
				</div>

				{/* Render */}
				{list.map((order) => {
					let color = "";
					switch (order.status) {
						case "Accepted":
							color = "text-primary";
							break;
						case "Rejected":
							color = "text-red";
							break;
						case "Delivered":
							color = "text-green-700";
							break;
						default:
							break;
					}
					return (
						<div
							className="flex h-auto w-full flex-col items-center justify-evenly border border-dashed border-gray text-sm font-bold text-white"
							key={order.id}>
							{/* Order ID */}
							<div className="flex w-full items-center justify-between px-4 py-4 text-gray">
								<p>Order id.</p>
								<p>{order.id}</p>
							</div>

							{/* Meal re-render */}
							{order.meals.map((meal) => (
								<div
									key={meal.id}
									className="flex w-full items-center justify-between px-4 py-4">
									<p>{meal.name}</p>
									<div className="flex flex-col gap-1 text-xs font-bold">
										<p className="flex items-center gap-1 font-semibold">
											<BsClockFill className=" text-xs text-primary" />
											{`${meal.minTime}-${meal.maxTime} min.`}
										</p>
										<p className="flex items-center  gap-1 font-semibold">
											<BsCashStack className=" text-xs text-primary" />
											{`${meal.price} XOF`}
										</p>
									</div>
								</div>
							))}

							<div className="flex w-full items-center justify-between px-4 py-4">
								<p>Total</p>
								<p className="text-xs font-semibold">
									{order.meals.reduce(
										(a: number, b: Meal) => a + b.price,
										0
									)}{" "}
									XOF
								</p>
							</div>

							<div className="flex h-auto w-full items-center justify-between bg-black px-4 py-4 text-end">
								<p className="">Status</p>
								<div className="flex flex-col items-end gap-1 text-xs font-bold">
									<p
										className={` ${color}
              text-xs font-semibold`}>
										{order.status}
									</p>
									{order.message && (
										<p className="max-w-sm break-words font-semibold text-gray">
											{order.message}
										</p>
									)}
								</div>
							</div>
						</div>
					);
				})}
			</div>
		</>
	);
};

export default App;
